language: node_js
node_js:
  - lts/*
script:
  - yarn build
  - yarn demo:build
install:
  - yarn
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: demo/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: false
  on:
    branch: main
